"""
=============================================================================
  MEDICAL RAG PIPELINE — Stage 4: Production Local Embedding Generator
=============================================================================
  Input  : chunks.json (generated by Stage 3 Semantic Chunk Builder)
  Output : embeddings.json (Vector embeddings + full metadata per chunk)

  Production Upgrades & Features
  ──────────────────────────────
  1. Strict Model Health Validation
     - Verifies Ollama server reachable on http://localhost:11434.
     - Verifies required model ('nomic-embed-text') is loaded.
     - Immediately aborts pipeline with clear error message if model is missing.

  2. Robust Retry Mechanism with Exponential Backoff
     - Up to 3 retries on HTTP errors, timeouts, or connection failures.
     - Delays: 1s, 2s, 4s before marking chunk as failed.

  3. Dynamic Vector Dimension Validation
     - Determines vector dimension dynamically from first valid embedding (768).
     - Validates all subsequent embeddings against this expected dimension.

  4. Generic Metadata Preservation & SHA-256 Content Hashing
     - Computes sha256 content hash for chunk modification tracking.
     - Automatically preserves all chunk metadata without fragile key lists.

  5. Strict Resume Validation & Self-Healing
     - Validates existing embeddings.json on startup.
     - Automatically discards outdated, corrupted, or dimension-mismatched
       records and re-embeds them automatically.

  6. Advanced Validation Engine & Performance Metrics
     - Checks duplicate IDs, duplicate vectors, empty content/vectors,
       invalid page ranges, invalid token counts, NaN/Inf corruption.
     - Reports throughput (chunks/sec), batch counts, latency, and totals.
=============================================================================
"""

from __future__ import annotations

import os
import sys
import json
import math
import time
import logging
import urllib.request
import urllib.error
import hashlib
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional, Tuple, Set


# ─────────────────────────────────────────────────────────────────────────────
# 0. CONFIGURATION DATASET
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class PipelineConfig:
    """Centralized configuration settings for the Embedding Pipeline."""
    model_name: str = "nomic-embed-text"
    ollama_host: str = "http://localhost:11434"
    input_path: str = "chunks.json"
    output_path: str = "embeddings.json"
    batch_size: int = 32
    timeout_seconds: int = 30
    max_retries: int = 3
    retry_delays: Tuple[int, ...] = (1, 2, 4)
    log_level: str = "INFO"


# Initialize Logger
config = PipelineConfig()
logging.basicConfig(
    level=getattr(logging, config.log_level),
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("EmbeddingGenerator")


def _safe_print(*args, **kwargs) -> None:
    """Drop-in replacement for print() that never crashes on console encoding errors."""
    try:
        print(*args, **kwargs)
    except UnicodeEncodeError:
        sep = kwargs.get("sep", " ")
        end = kwargs.get("end", "\n")
        file = kwargs.get("file", sys.stdout)
        msg = sep.join(str(a) for a in args) + end
        msg = msg.replace("✅", "[OK]").replace("⚠️", "[WARN]").replace("❌", "[FAIL]").replace("✓", "[PASS]")
        enc = getattr(file, "encoding", "ascii") or "ascii"
        try:
            file.buffer.write(msg.encode(enc, errors="replace"))
        except Exception:
            pass


# ─────────────────────────────────────────────────────────────────────────────
# 1. DATA MODELS & UTILITIES
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class EmbeddedRecord:
    """Complete embedded record format matching Vector DB output schema."""
    chunk_id: str
    embedding: List[float]
    metadata: Dict[str, Any]
    content: str
    table_references: List[str] = field(default_factory=list)
    figure_references: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "chunk_id": self.chunk_id,
            "embedding": self.embedding,
            "metadata": self.metadata,
            "content": self.content,
            "table_references": self.table_references,
            "figure_references": self.figure_references
        }


def compute_content_hash(content: str) -> str:
    """Generates SHA-256 digest of chunk text for content modification detection."""
    return hashlib.sha256(content.strip().encode("utf-8")).hexdigest()


def construct_embedding_text(chunk: dict) -> str:
    """
    Constructs hierarchical text representation before embedding generation.
    Incorporating Chapter/Section headings into vector space improves retrieval precision.
    """
    header_parts = []
    doc_title = chunk.get("document_title", "").strip()
    chapter = chunk.get("chapter", "").strip()
    section = chunk.get("section", "").strip()
    subsection = chunk.get("subsection", "").strip()

    if doc_title:
        header_parts.append(f"Document: {doc_title}")
    if chapter:
        header_parts.append(f"Chapter: {chapter}")
    if section:
        header_parts.append(f"Section: {section}")
    if subsection:
        header_parts.append(f"Subsection: {subsection}")

    hierarchy_prefix = "\n".join(header_parts)
    content = chunk.get("content", "").strip()

    return f"{hierarchy_prefix}\n\nContent:\n{content}".strip()


# ─────────────────────────────────────────────────────────────────────────────
# 2. OLLAMA EMBEDDING CLIENT WITH EXPONENTIAL RETRIES
# ─────────────────────────────────────────────────────────────────────────────

class OllamaEmbeddingClient:
    """Robust local Ollama Client supporting batched vector embeddings & retries."""

    def __init__(self, cfg: PipelineConfig = config):
        self.cfg = cfg
        self.host = cfg.ollama_host.rstrip("/")
        self.model = cfg.model_name

    def validate_health(self) -> None:
        """
        Verifies Ollama server is reachable and requested embedding model exists.
        Raises RuntimeError immediately if server or model is unavailable.
        """
        url = f"{self.host}/api/tags"
        try:
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=5) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                models = [m.get("name", "") for m in data.get("models", [])]
                model_base = self.model.split(":")[0]
                has_model = any(model_base in m for m in models)
                if not has_model:
                    raise RuntimeError(
                        f"❌ CRITICAL ERROR: Required embedding model '{self.model}' is NOT installed in Ollama.\n"
                        f"Available models: {models}\n"
                        f"Please run 'ollama pull {self.model}' in your terminal before restarting."
                    )
                logger.info(f"Ollama health check passed: Model '{self.model}' is ready.")
        except urllib.error.URLError as e:
            raise RuntimeError(f"❌ CRITICAL ERROR: Ollama server is unreachable at {self.host} ({e.reason}). Ensure Ollama is running.") from e
        except Exception as e:
            if "CRITICAL ERROR" in str(e):
                raise
            raise RuntimeError(f"❌ CRITICAL ERROR: Ollama server check failed: {e}") from e

    def embed_batch(self, texts: List[str]) -> Tuple[List[Optional[List[float]]], float]:
        """
        Embed a batch of texts using Ollama batch API (/api/embed) with exponential retry.
        Returns (list_of_embeddings, total_latency_seconds).
        """
        if not texts:
            return [], 0.0

        url = f"{self.host}/api/embed"
        payload = json.dumps({"model": self.model, "input": texts}).encode("utf-8")

        for attempt in range(1, self.cfg.max_retries + 1):
            t0 = time.time()
            try:
                req = urllib.request.Request(
                    url,
                    data=payload,
                    headers={"Content-Type": "application/json"}
                )
                with urllib.request.urlopen(req, timeout=self.cfg.timeout_seconds) as resp:
                    res = json.loads(resp.read().decode("utf-8"))
                    embeddings = res.get("embeddings", [])
                    latency = time.time() - t0
                    if len(embeddings) == len(texts):
                        return embeddings, latency
            except Exception as e:
                delay = self.cfg.retry_delays[min(attempt - 1, len(self.cfg.retry_delays) - 1)]
                logger.warning(
                    f"Batch embedding request attempt {attempt}/{self.cfg.max_retries} failed ({e}). "
                    f"Retrying in {delay}s..."
                )
                time.sleep(delay)

        # Fallback to single requests if batch call fails after retries
        logger.info("Batch endpoint failed after retries. Attempting single requests fallback...")
        results = []
        t0 = time.time()
        for text in texts:
            emb = self.embed_single(text)
            results.append(emb)
        return results, time.time() - t0

    def embed_single(self, text: str) -> Optional[List[float]]:
        """Embed a single text string using /api/embeddings with retry."""
        url = f"{self.host}/api/embeddings"
        payload = json.dumps({"model": self.model, "prompt": text}).encode("utf-8")

        for attempt in range(1, self.cfg.max_retries + 1):
            try:
                req = urllib.request.Request(
                    url,
                    data=payload,
                    headers={"Content-Type": "application/json"}
                )
                with urllib.request.urlopen(req, timeout=self.cfg.timeout_seconds) as resp:
                    res = json.loads(resp.read().decode("utf-8"))
                    return res.get("embedding", None)
            except Exception as e:
                delay = self.cfg.retry_delays[min(attempt - 1, len(self.cfg.retry_delays) - 1)]
                logger.warning(f"Single embedding request attempt {attempt} failed ({e}). Retrying in {delay}s...")
                time.sleep(delay)

        logger.error("Single embedding request failed after all retries.")
        return None


# ─────────────────────────────────────────────────────────────────────────────
# 3. PRODUCTION EMBEDDING PIPELINE
# ─────────────────────────────────────────────────────────────────────────────

class EmbeddingPipeline:
    """Production-grade Embedding Pipeline with validation, resumability, and metrics."""

    def __init__(self, cfg: PipelineConfig = config):
        self.cfg = cfg
        self.client = OllamaEmbeddingClient(cfg=cfg)
        self.expected_dimension: Optional[int] = None

    def run(self) -> List[EmbeddedRecord]:
        """Executes complete embedding pipeline with strict health & resume checks."""
        start_time = time.time()
        logger.info(f"Starting Embedding Pipeline with model '{self.cfg.model_name}'...")

        # 1. Health & Model Validation
        self.client.validate_health()

        # 2. Load input chunks
        if not os.path.exists(self.cfg.input_path):
            raise FileNotFoundError(f"Input file not found: {self.cfg.input_path}")

        with open(self.cfg.input_path, "r", encoding="utf-8") as f:
            raw_chunks = json.load(f)

        logger.info(f"Loaded {len(raw_chunks)} chunks from {self.cfg.input_path}.")
        chunk_map = {c["chunk_id"]: c for c in raw_chunks}

        # 3. Resume Validation & Self-Healing
        existing_records, valid_existing_records = self._load_and_validate_existing(chunk_map)
        logger.info(f"Resumability: {len(valid_existing_records)} / {len(raw_chunks)} records validated from disk.")

        # Establish expected dimension from valid existing records if available
        if valid_existing_records:
            first_emb = valid_existing_records[0].embedding
            if first_emb:
                self.expected_dimension = len(first_emb)
                logger.info(f"Established vector dimension from existing records: {self.expected_dimension}")

        # Determine remaining chunks needing embedding
        valid_ids = {r.chunk_id for r in valid_existing_records}
        remaining_chunks = [c for c in raw_chunks if c["chunk_id"] not in valid_ids]
        logger.info(f"Generating embeddings for {len(remaining_chunks)} remaining chunk(s)...")

        embedded_records: List[EmbeddedRecord] = list(valid_existing_records)
        failed_count = 0
        total_chunks = len(raw_chunks)
        processed_count = len(valid_existing_records)

        # Performance tracking metrics
        total_batches = 0
        successful_batches = 0
        failed_batches = 0
        batch_times: List[float] = []

        # 4. Batched Embedding Generation
        for i in range(0, len(remaining_chunks), self.cfg.batch_size):
            total_batches += 1
            batch_chunks = remaining_chunks[i : i + self.cfg.batch_size]
            batch_texts = [construct_embedding_text(c) for c in batch_chunks]

            batch_embeddings, latency = self.client.embed_batch(batch_texts)
            batch_times.append(latency)

            valid_in_batch = 0
            for j, chunk in enumerate(batch_chunks):
                emb = batch_embeddings[j] if j < len(batch_embeddings) else None

                if emb and len(emb) > 0:
                    # Dynamically set expected dimension from first generated vector
                    if self.expected_dimension is None:
                        self.expected_dimension = len(emb)
                        logger.info(f"Dynamic Vector Dimension set: {self.expected_dimension}")

                    # Automatically preserve ALL generic metadata fields + compute SHA-256 hash
                    meta = {}
                    for k, v in chunk.items():
                        if k not in ("content", "embedding", "chunk_id", "table_references", "figure_references"):
                            meta[k] = v
                    meta["content_hash"] = compute_content_hash(chunk.get("content", ""))

                    rec = EmbeddedRecord(
                        chunk_id=chunk["chunk_id"],
                        embedding=emb,
                        metadata=meta,
                        content=chunk.get("content", ""),
                        table_references=chunk.get("table_references", []),
                        figure_references=chunk.get("figure_references", [])
                    )
                    embedded_records.append(rec)
                    valid_in_batch += 1
                else:
                    logger.error(f"Failed chunk id: {chunk['chunk_id']}")
                    failed_count += 1

                processed_count += 1
                _safe_print(f"Embedding chunk {processed_count} / {total_chunks}")

            if valid_in_batch == len(batch_chunks):
                successful_batches += 1
            else:
                failed_batches += 1

            # Incremental save after every batch
            self._save_output(embedded_records)

        total_time = time.time() - start_time
        logger.info("Embedding processing completed.")

        # 5. Extended Validation & Performance Report
        self._validate_and_report(
            raw_chunks=raw_chunks,
            records=embedded_records,
            failed_count=failed_count,
            total_time=total_time,
            total_batches=total_batches,
            successful_batches=successful_batches,
            failed_batches=failed_batches,
            batch_times=batch_times
        )

        return embedded_records

    def _load_and_validate_existing(self, chunk_map: Dict[str, dict]) -> Tuple[List[EmbeddedRecord], List[EmbeddedRecord]]:
        """Loads and strictly validates existing embeddings.json records against input chunks."""
        if not os.path.exists(self.cfg.output_path):
            return [], []

        raw_existing = []
        try:
            with open(self.cfg.output_path, "r", encoding="utf-8") as f:
                raw_existing = json.load(f)
        except Exception as e:
            logger.warning(f"Could not read existing {self.cfg.output_path}: {e}")
            return [], []

        valid_records = []
        seen_ids = set()

        for item in raw_existing:
            chk_id = item.get("chunk_id")
            emb = item.get("embedding")
            meta = item.get("metadata", {})
            content = item.get("content", "")

            # Check 1: Must exist in input chunk map
            if not chk_id or chk_id not in chunk_map:
                logger.info(f"Resume Validation: Discarding obsolete chunk_id '{chk_id}'")
                continue

            # Check 2: Must be unique
            if chk_id in seen_ids:
                logger.info(f"Resume Validation: Discarding duplicate chunk_id '{chk_id}'")
                continue
            seen_ids.add(chk_id)

            # Check 3: Content Hash Match
            orig_chunk = chunk_map[chk_id]
            expected_hash = compute_content_hash(orig_chunk.get("content", ""))
            stored_hash = meta.get("content_hash", "")

            if stored_hash and stored_hash != expected_hash:
                logger.info(f"Resume Validation: Chunk content modified for '{chk_id}'. Discarding old embedding.")
                continue

            # Check 4: Vector integrity
            if not emb or not isinstance(emb, list) or len(emb) == 0:
                logger.info(f"Resume Validation: Discarding empty embedding vector for '{chk_id}'")
                continue

            if any(math.isnan(x) or math.isinf(x) for x in emb if isinstance(x, (int, float))):
                logger.info(f"Resume Validation: Discarding corrupted vector (NaN/Inf) for '{chk_id}'")
                continue

            rec = EmbeddedRecord(
                chunk_id=chk_id,
                embedding=emb,
                metadata=meta,
                content=content,
                table_references=item.get("table_references", []),
                figure_references=item.get("figure_references", [])
            )
            valid_records.append(rec)

        return [EmbeddedRecord(**i) for i in raw_existing if "chunk_id" in i], valid_records

    def _save_output(self, records: List[EmbeddedRecord]) -> None:
        """Saves current record list to output JSON file."""
        dict_output = [r.to_dict() for r in records]
        with open(self.cfg.output_path, "w", encoding="utf-8") as f:
            json.dump(dict_output, f, indent=2, ensure_ascii=False)

    def _validate_and_report(
        self,
        raw_chunks: list,
        records: List[EmbeddedRecord],
        failed_count: int,
        total_time: float,
        total_batches: int,
        successful_batches: int,
        failed_batches: int,
        batch_times: List[float]
    ) -> None:
        """Executes comprehensive production validation checks and outputs structured metrics report."""
        loaded_count = len(raw_chunks)
        embedded_count = len(records)

        # Vector dimension check
        dimensions = {len(r.embedding) for r in records if r.embedding}
        inconsistent_dims = len(dimensions) > 1
        dim_str = str(list(dimensions)[0]) if len(dimensions) == 1 else str(list(dimensions))

        # Check duplicate chunk IDs
        chunk_ids = [r.chunk_id for r in records]
        duplicates_count = len(chunk_ids) - len(set(chunk_ids))

        # Check duplicate embeddings (exact vector match)
        vector_hashes = {tuple(r.embedding) for r in records if r.embedding}
        duplicate_vectors_count = len(records) - len(vector_hashes)

        # Check empty content & embeddings
        empty_content_count = sum(1 for r in records if not r.content or not r.content.strip())
        empty_embeddings_count = sum(1 for r in records if not r.embedding or len(r.embedding) == 0)

        # Check NaN/Inf corrupted vectors
        corrupted_vectors_count = sum(
            1 for r in records
            if any(math.isnan(x) or math.isinf(x) for x in r.embedding if isinstance(x, (int, float)))
        )

        # Check metadata fields
        missing_metadata_count = sum(
            1 for r in records
            if not r.metadata or "page_start" not in r.metadata or "content_hash" not in r.metadata
        )

        # Check invalid page ranges
        invalid_page_ranges = sum(
            1 for r in records
            if r.metadata.get("page_start", 1) > r.metadata.get("page_end", 1) or r.metadata.get("page_start", 1) < 1
        )

        # Check invalid token counts
        invalid_token_counts = sum(
            1 for r in records
            if r.metadata.get("token_count", 0) <= 0
        )

        # Metrics calculation
        avg_batch_time = (sum(batch_times) / len(batch_times)) if batch_times else 0.0
        avg_chunk_latency = (total_time / loaded_count * 1000) if loaded_count > 0 else 0.0
        throughput = (embedded_count / total_time) if total_time > 0 else 0.0

        _safe_print("\n" + "=" * 72)
        _safe_print("  PRODUCTION EMBEDDING GENERATOR REPORT")
        _safe_print("=" * 72)
        _safe_print(f"  ✓ Chunks Loaded             : {loaded_count}")
        _safe_print(f"  ✓ Successfully Embedded    : {embedded_count}")
        _safe_print(f"  ✓ Failures                 : {failed_count}")
        _safe_print(f"  ✓ Dynamic Embedding Dim    : {dim_str}")
        _safe_print("-" * 72)
        _safe_print("  PERFORMANCE METRICS")
        _safe_print(f"  ✓ Total Processing Time   : {total_time:.2f} sec")
        _safe_print(f"  ✓ Throughput               : {throughput:.2f} chunks/sec")
        _safe_print(f"  ✓ Avg Request Latency     : {avg_chunk_latency:.2f} ms/chunk")
        _safe_print(f"  ✓ Avg Batch Latency       : {avg_batch_time:.2f} sec/batch")
        _safe_print(f"  ✓ Total Batches           : {total_batches}")
        _safe_print(f"  ✓ Successful Batches      : {successful_batches}")
        _safe_print(f"  ✓ Failed Batches          : {failed_batches}")
        _safe_print("-" * 72)
        _safe_print("  INTEGRITY & VALIDATION CHECKS")
        _safe_print(f"  ✓ Duplicate Chunk IDs      : {duplicates_count}")
        _safe_print(f"  ✓ Duplicate Vectors        : {duplicate_vectors_count}")
        _safe_print(f"  ✓ Empty Content            : {empty_content_count}")
        _safe_print(f"  ✓ Empty Embeddings         : {empty_embeddings_count}")
        _safe_print(f"  ✓ Corrupted (NaN/Inf)      : {corrupted_vectors_count}")
        _safe_print(f"  ✓ Missing Metadata          : {missing_metadata_count}")
        _safe_print(f"  ✓ Invalid Page Ranges      : {invalid_page_ranges}")
        _safe_print(f"  ✓ Invalid Token Counts     : {invalid_token_counts}")
        _safe_print(f"  ✓ Inconsistent Dimensions  : {'YES [FAIL]' if inconsistent_dims else 'NO [PASS]'}")
        _safe_print("-" * 72)

        is_valid = (
            embedded_count > 0 and
            failed_count == 0 and
            duplicates_count == 0 and
            empty_content_count == 0 and
            empty_embeddings_count == 0 and
            corrupted_vectors_count == 0 and
            missing_metadata_count == 0 and
            not inconsistent_dims
        )
        _safe_print("  Validation Status           : " + ("✅ PASSED (Production Ready)" if is_valid else "⚠️ WARNINGS DETECTED"))
        _safe_print("=" * 72 + "\n")


# ─────────────────────────────────────────────────────────────────────────────
# 6. ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    pipeline = EmbeddingPipeline()
    pipeline.run()
