"""
=============================================================================
  MEDICAL RAG PIPELINE — Stage 4: Local Embedding Generator (Ollama)
=============================================================================
  Input  : chunks.json (generated by Stage 3 Semantic Chunk Builder)
  Output : embeddings.json (Vector embeddings + full metadata per chunk)

  Architecture & Design Principles
  ────────────────────────────────
  1. Local Only (Ollama / nomic-embed-text)
     - Runs 100% locally on Ollama (http://localhost:11434/api/embed).
     - Zero cloud dependencies, zero external APIs.

  2. Contextual Hierarchy Construct
     - Embeds prepended hierarchy text (Document -> Chapter -> Section -> Content)
       for enhanced vector search relevance.

  3. Full Metadata Preservation
     - Preserves chunk_id, metadata (title, chapter, section, pages, tokens),
       content, table_references, and figure_references.

  4. Batched Execution & Live Progress
     - Configurable batch size (default 32).
     - Live progress logging (e.g., "Embedding chunk 32 / 90").

  5. Resilience & Resumability
     - Skips failing chunks gracefully without crashing pipeline.
     - Automatically resumes from existing embeddings.json on rerun.

  6. Comprehensive Validation Engine
     - Checks vector dimension (768), empty vectors, missing metadata,
       duplicate chunk IDs, total time, and per-chunk latency.
=============================================================================
"""

from __future__ import annotations

import os
import sys
import json
import time
import logging
import urllib.request
import urllib.error
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Any, Optional, Tuple, Set


# ─────────────────────────────────────────────────────────────────────────────
# 0. CONFIGURATION CONSTANTS
# ─────────────────────────────────────────────────────────────────────────────

EMBEDDING_MODEL: str = "nomic-embed-text"
OLLAMA_HOST: str = "http://localhost:11434"
INPUT_PATH: str = "chunks.json"
OUTPUT_PATH: str = "embeddings.json"
BATCH_SIZE: int = 32
LOG_LEVEL: str = "INFO"


# Configure logging
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL),
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("EmbeddingGenerator")


def _safe_print(*args, **kwargs) -> None:
    """Drop-in replacement for print() that never crashes on encoding errors."""
    try:
        print(*args, **kwargs)
    except UnicodeEncodeError:
        sep = kwargs.get("sep", " ")
        end = kwargs.get("end", "\n")
        file = kwargs.get("file", sys.stdout)
        msg = sep.join(str(a) for a in args) + end
        msg = msg.replace("✅", "[OK]").replace("⚠️", "[WARN]").replace("❌", "[FAIL]")
        enc = getattr(file, "encoding", "ascii") or "ascii"
        try:
            file.buffer.write(msg.encode(enc, errors="replace"))
        except Exception:
            pass


# ─────────────────────────────────────────────────────────────────────────────
# 1. DATA MODELS
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class EmbeddedRecord:
    """Complete embedded record format matching Vector DB output schema."""
    chunk_id: str
    embedding: List[float]
    metadata: Dict[str, Any]
    content: str
    table_references: List[str] = field(default_factory=list)
    figure_references: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "chunk_id": self.chunk_id,
            "embedding": self.embedding,
            "metadata": self.metadata,
            "content": self.content,
            "table_references": self.table_references,
            "figure_references": self.figure_references
        }


# ─────────────────────────────────────────────────────────────────────────────
# 2. CONTEXTUAL HIERARCHY CONSTRUCT
# ─────────────────────────────────────────────────────────────────────────────

def construct_embedding_text(chunk: dict) -> str:
    """
    Constructs hierarchical text representation before embedding generation.
    Incorporating Chapter/Section headings into vector space improves search retrieval quality.
    """
    header_parts = []
    doc_title = chunk.get("document_title", "").strip()
    chapter = chunk.get("chapter", "").strip()
    section = chunk.get("section", "").strip()
    subsection = chunk.get("subsection", "").strip()

    if doc_title:
        header_parts.append(f"Document: {doc_title}")
    if chapter:
        header_parts.append(f"Chapter: {chapter}")
    if section:
        header_parts.append(f"Section: {section}")
    if subsection:
        header_parts.append(f"Subsection: {subsection}")

    hierarchy_prefix = "\n".join(header_parts)
    content = chunk.get("content", "").strip()

    return f"{hierarchy_prefix}\n\nContent:\n{content}".strip()


# ─────────────────────────────────────────────────────────────────────────────
# 3. OLLAMA EMBEDDING CLIENT
# ─────────────────────────────────────────────────────────────────────────────

class OllamaEmbeddingClient:
    """Local Ollama Client supporting batched vector embedding generation."""

    def __init__(self, host: str = OLLAMA_HOST, model: str = EMBEDDING_MODEL):
        self.host = host.rstrip("/")
        self.model = model

    def check_health(self) -> bool:
        """Verify Ollama server is running and requested model is available."""
        url = f"{self.host}/api/tags"
        try:
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=5) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                models = [m.get("name", "") for m in data.get("models", [])]
                model_base = self.model.split(":")[0]
                has_model = any(model_base in m for m in models)
                if not has_model:
                    logger.warning(f"Model '{self.model}' not found in Ollama tags. Available: {models}")
                return True
        except Exception as e:
            logger.error(f"Cannot connect to Ollama at {url}: {e}")
            return False

    def embed_batch(self, texts: List[str]) -> List[Optional[List[float]]]:
        """
        Embed a batch of texts using Ollama batch API (/api/embed).
        Falls back to individual calls (/api/embeddings) if batch endpoint is unsupported.
        """
        if not texts:
            return []

        # Try batch /api/embed endpoint
        url = f"{self.host}/api/embed"
        payload = json.dumps({
            "model": self.model,
            "input": texts
        }).encode("utf-8")

        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"}
        )

        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                res = json.loads(resp.read().decode("utf-8"))
                embeddings = res.get("embeddings", [])
                if len(embeddings) == len(texts):
                    return embeddings
        except Exception as e:
            logger.debug(f"Batch endpoint /api/embed call failed: {e}. Falling back to single requests.")

        # Fallback: process individually
        results = []
        for text in texts:
            results.append(self.embed_single(text))
        return results

    def embed_single(self, text: str) -> Optional[List[float]]:
        """Embed a single text string using /api/embeddings."""
        url = f"{self.host}/api/embeddings"
        payload = json.dumps({
            "model": self.model,
            "prompt": text
        }).encode("utf-8")

        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"}
        )

        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                res = json.loads(resp.read().decode("utf-8"))
                return res.get("embedding", None)
        except Exception as e:
            logger.error(f"Failed to embed single text snippet: {e}")
            return None


# ─────────────────────────────────────────────────────────────────────────────
# 4. PIPELINE PIPELINING ENGINE
# ─────────────────────────────────────────────────────────────────────────────

class EmbeddingPipeline:
    """Production Embedding Pipeline with batching, validation, and resumability."""

    def __init__(
        self,
        input_path: str = INPUT_PATH,
        output_path: str = OUTPUT_PATH,
        batch_size: int = BATCH_SIZE,
        model_name: str = EMBEDDING_MODEL,
        host: str = OLLAMA_HOST
    ):
        self.input_path = input_path
        self.output_path = output_path
        self.batch_size = batch_size
        self.client = OllamaEmbeddingClient(host=host, model=model_name)

    def run(self) -> List[EmbeddedRecord]:
        """Execute complete embedding generation pipeline."""
        start_time = time.time()
        logger.info(f"Loading chunks from {self.input_path}...")

        if not os.path.exists(self.input_path):
            raise FileNotFoundError(f"Input chunk file not found: {self.input_path}")

        with open(self.input_path, "r", encoding="utf-8") as f:
            raw_chunks = json.load(f)

        logger.info(f"Loaded {len(raw_chunks)} chunks from {self.input_path}.")

        # Check Ollama connection
        if not self.client.check_health():
            raise RuntimeError(f"Ollama server is not accessible at {self.client.host}")

        # Resumability: Load existing embeddings if output_path exists
        existing_records: Dict[str, EmbeddedRecord] = {}
        if os.path.exists(self.output_path):
            try:
                with open(self.output_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    for item in data:
                        rec = EmbeddedRecord(
                            chunk_id=item["chunk_id"],
                            embedding=item["embedding"],
                            metadata=item["metadata"],
                            content=item["content"],
                            table_references=item.get("table_references", []),
                            figure_references=item.get("figure_references", [])
                        )
                        existing_records[rec.chunk_id] = rec
                logger.info(f"Resumability: Loaded {len(existing_records)} existing embeddings from {self.output_path}")
            except Exception as e:
                logger.warning(f"Could not load existing embeddings file: {e}")

        remaining_chunks = [c for c in raw_chunks if c["chunk_id"] not in existing_records]
        logger.info(f"Generating embeddings for {len(remaining_chunks)} remaining chunk(s)...")

        embedded_list: List[EmbeddedRecord] = list(existing_records.values())
        failed_count = 0
        total_chunks = len(raw_chunks)
        processed_count = len(existing_records)

        # Process in batches
        for i in range(0, len(remaining_chunks), self.batch_size):
            batch_chunks = remaining_chunks[i : i + self.batch_size]
            batch_texts = [construct_embedding_text(c) for c in batch_chunks]

            batch_embeddings = self.client.embed_batch(batch_texts)

            for j, chunk in enumerate(batch_chunks):
                emb = batch_embeddings[j] if j < len(batch_embeddings) else None

                if emb is not None and len(emb) > 0:
                    metadata = {
                        "document_title": chunk.get("document_title", ""),
                        "chapter": chunk.get("chapter", ""),
                        "section": chunk.get("section", ""),
                        "subsection": chunk.get("subsection", ""),
                        "page_start": chunk.get("page_start", 1),
                        "page_end": chunk.get("page_end", 1),
                        "token_count": chunk.get("token_count", 0)
                    }

                    rec = EmbeddedRecord(
                        chunk_id=chunk["chunk_id"],
                        embedding=emb,
                        metadata=metadata,
                        content=chunk.get("content", ""),
                        table_references=chunk.get("table_references", []),
                        figure_references=chunk.get("figure_references", [])
                    )
                    embedded_list.append(rec)
                else:
                    logger.error(f"Failed chunk id: {chunk['chunk_id']}")
                    failed_count += 1

                processed_count += 1
                _safe_print(f"Embedding chunk {processed_count} / {total_chunks}")

            # Save progress incrementally after each batch
            self._save_output(embedded_list)

        total_time = time.time() - start_time
        logger.info("Embedding completed.")

        # Run Validation Engine
        self._validate_results(raw_chunks, embedded_list, failed_count, total_time)

        return embedded_list

    def _save_output(self, records: List[EmbeddedRecord]) -> None:
        """Save list of EmbeddedRecord to output JSON file."""
        dict_output = [r.to_dict() for r in records]
        with open(self.output_path, "w", encoding="utf-8") as f:
            json.dump(dict_output, f, indent=2, ensure_ascii=False)

    def _validate_results(
        self,
        raw_chunks: list,
        records: List[EmbeddedRecord],
        failed_count: int,
        total_time: float
    ) -> None:
        """Runs comprehensive validation checks and prints summary report."""
        loaded_count = len(raw_chunks)
        success_count = len(records)

        # Compute dimension
        dimensions = {len(r.embedding) for r in records if r.embedding}
        dim_str = str(list(dimensions)[0]) if len(dimensions) == 1 else str(list(dimensions))

        # Check duplicate chunk IDs
        chunk_ids = [r.chunk_id for r in records]
        duplicates_count = len(chunk_ids) - len(set(chunk_ids))

        # Check empty embeddings
        empty_embeddings_count = sum(1 for r in records if not r.embedding or len(r.embedding) == 0)

        # Check missing metadata
        missing_meta_count = sum(
            1 for r in records
            if not r.metadata or "page_start" not in r.metadata or "token_count" not in r.metadata
        )

        avg_time_ms = (total_time / loaded_count * 1000) if loaded_count > 0 else 0.0

        _safe_print("\n" + "=" * 72)
        _safe_print("  EMBEDDING GENERATOR VALIDATION REPORT")
        _safe_print("=" * 72)
        _safe_print(f"  ✓ Chunks Loaded             : {loaded_count}")
        _safe_print(f"  ✓ Successfully Embedded    : {success_count}")
        _safe_print(f"  ✓ Failures                 : {failed_count}")
        _safe_print(f"  ✓ Embedding Dimension      : {dim_str}")
        _safe_print(f"  ✓ Avg Time per Chunk       : {avg_time_ms:.2f} ms")
        _safe_print(f"  ✓ Total Processing Time   : {total_time:.2f} sec")
        _safe_print(f"  ✓ Duplicate Chunk IDs      : {duplicates_count}")
        _safe_print(f"  ✓ Empty Embeddings         : {empty_embeddings_count}")
        _safe_print(f"  ✓ Missing Metadata          : {missing_meta_count}")
        _safe_print("-" * 72)
        
        is_valid = (
            success_count > 0 and
            failed_count == 0 and
            duplicates_count == 0 and
            empty_embeddings_count == 0 and
            missing_meta_count == 0
        )
        _safe_print("  Validation Status           : " + ("✅ PASSED (0 failures, 100% embedded)" if is_valid else "⚠️ WARNINGS DETECTED"))
        _safe_print("=" * 72 + "\n")


# ─────────────────────────────────────────────────────────────────────────────
# 5. ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    pipeline = EmbeddingPipeline(
        input_path=INPUT_PATH,
        output_path=OUTPUT_PATH,
        batch_size=BATCH_SIZE,
        model_name=EMBEDDING_MODEL,
        host=OLLAMA_HOST
    )
    pipeline.run()
